# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cec9a929d717fa90e35e8c6ba73fbe14d4a1f193668ce4cb09ca2db09d6d4050d6feca586a00a7b27290eee06ed303829cbf7f52ed80011c279aa6f79db3b86

test:
  secret_key_base: f51d60da4a6e2b3360ad45da5c69c48c2113fe802468afea94fe806f812e5a0acc786037cd15b41c5ce4243aab070ac1b251ca79a48de68a83c9333e05016d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
